"""SSH connection manager.

Every host gets one multiplexed master connection (ControlMaster) opened at
app start. Terminals, metric probes, inventory scans and blueprint runs all
ride that single socket, so after the first handshake a remote command costs
about as much as a local fork -- which is what makes the UI feel live.

Auth is deliberately catch-all: agent, explicit key (with or without a
passphrase), password, and any combination behind a ProxyJump. Passwords and
passphrases are handed to ssh through SSH_ASKPASS rather than a command line
or a file, so they never appear in `ps` output or on disk.
"""
import os
import re
import shlex
import subprocess
import threading
import time
from concurrent.futures import ThreadPoolExecutor

import boundedproc
import hosts as hostreg
import secretsvc
import vpn
from paths import ASKPASS, SSH_CONFIG, control_path, ensure_dirs

SSH = "/usr/bin/ssh"
SCP = "/usr/bin/scp"
SFTP = "/usr/bin/sftp"
SSH_KEYGEN = "/usr/bin/ssh-keygen"
SSH_COPY_ID = "/usr/bin/ssh-copy-id" if os.access("/usr/bin/ssh-copy-id", os.X_OK) else None

_state_lock = threading.RLock()
_state = {}        # host_id -> {status, error, since, latency_ms}
_connect_locks = {}


ASKPASS_SCRIPT = r"""#!/bin/sh
# Written by Fleet. Answers ssh's interactive prompts from the environment so
# no credential is ever passed on a command line or written to disk.
prompt="$1"
case "$prompt" in
  *[Ff]ingerprint*|*"(yes/no"*|*"yes/no/[fingerprint]"*) printf 'yes\n' ;;
  *assphrase*) printf '%s\n' "${FLEET_PASSPHRASE:-$FLEET_PASSWORD}" ;;
  *) printf '%s\n' "$FLEET_PASSWORD" ;;
esac
"""


def bootstrap():
    ensure_dirs()
    with open(ASKPASS, "w") as fh:
        fh.write(ASKPASS_SCRIPT)
    os.chmod(ASKPASS, 0o700)
    write_ssh_config()


# ------------------------------------------------------------- ssh_config gen

def alias(host):
    return "f-" + host["id"]


# An ssh_config value is a line in a file that ssh executes directives from.
# A newline in a hostname therefore injects a directive -- ProxyCommand being
# the obvious one -- so every value is validated before it is written, and a
# bad one drops its directive rather than being silently mangled into
# something that still runs.
_CFG_SAFE = re.compile(r"^[A-Za-z0-9_.:@/%~\[\]+=-]+$")
_CFG_KEY = re.compile(r"^[A-Za-z][A-Za-z0-9]*$")


def cfg_value(value, allow_spaces=False):
    """Return a value safe to write into ssh_config, or None if it is not."""
    v = str(value if value is not None else "").strip()
    if not v or "\n" in v or "\r" in v:
        return None
    if allow_spaces:
        # Quoted form: ssh accepts "..." for paths with spaces. Reject quotes
        # and backslashes so the quoting cannot be broken out of.
        if any(c in v for c in '"\\\n\r'):
            return None
        return '"%s"' % v if " " in v else v
    return v if _CFG_SAFE.match(v) else None


def _block(h):
    hostname = cfg_value(h.get("hostname")) or "localhost"
    user = cfg_value(h.get("user")) or "root"
    try:
        port = int(h.get("port") or 22)
    except (TypeError, ValueError):
        port = 22
    port = port if 1 <= port <= 65535 else 22

    lines = ["Host %s" % alias(h),
             "  HostName %s" % hostname,
             "  User %s" % user,
             "  Port %d" % port,
             "  ControlMaster auto",
             "  ControlPath %s" % control_path(h["id"]),
             "  ControlPersist 30m",
             "  ServerAliveInterval 15",
             "  ServerAliveCountMax 3",
             "  ConnectTimeout 12",
             "  StrictHostKeyChecking accept-new",
             "  TCPKeepAlive yes"]
    if h["auth"] == "key" and h.get("identity_file"):
        ident = cfg_value(h["identity_file"], allow_spaces=True)
        if ident:
            lines += ["  IdentityFile %s" % ident, "  IdentitiesOnly yes"]
    elif h["auth"] == "password":
        lines += ["  PreferredAuthentications password,keyboard-interactive",
                  "  PubkeyAuthentication no",
                  "  NumberOfPasswordPrompts 1"]
    if h.get("proxy_jump"):
        jump = cfg_value(h["proxy_jump"])
        if jump:
            lines.append("  ProxyJump %s" % jump)
    for k, v in (h.get("options") or {}).items():
        # ProxyCommand and friends run programs; a user editing hosts.json by
        # hand may set them deliberately, but they never come from the UI, so
        # the value still has to survive validation to be written.
        key, val = str(k).strip(), cfg_value(v, allow_spaces=True)
        if _CFG_KEY.match(key) and val:
            lines.append("  %s %s" % (key, val))
    return "\n".join(lines)


def write_ssh_config():
    blocks = [_block(h) for h in hostreg.load()]
    header = ("# Generated by Fleet -- edits are overwritten.\n"
              "# Host definitions live in ~/.config/fleet/hosts.json\n\n")
    tmp = SSH_CONFIG + ".tmp"
    with open(tmp, "w") as fh:
        fh.write(header + "\n\n".join(blocks) + "\n")
    os.chmod(tmp, 0o600)
    os.replace(tmp, SSH_CONFIG)


# -------------------------------------------------------------------- env

def env_for(host, interactive=False):
    env = dict(os.environ)
    env["FLEET_PASSWORD"] = ""
    env["FLEET_PASSPHRASE"] = ""
    if host["auth"] == "password":
        env["FLEET_PASSWORD"] = secretsvc.get_secret("pw:" + host["id"]) or ""
    ph = secretsvc.get_secret("ph:" + host["id"])
    if ph:
        env["FLEET_PASSPHRASE"] = ph
    env["SSH_ASKPASS"] = ASKPASS
    env["SSH_ASKPASS_REQUIRE"] = "force"
    env.setdefault("DISPLAY", ":0")
    if interactive:
        env["TERM"] = "xterm-256color"
    return env


def base_args(host):
    return [SSH, "-F", SSH_CONFIG, alias(host)]


# ------------------------------------------------------------------- state

def get_state(host_id):
    with _state_lock:
        return dict(_state.get(host_id) or
                    {"status": "idle", "error": "", "since": 0, "detail": ""})


def set_state(host_id, **kw):
    with _state_lock:
        s = _state.setdefault(host_id, {"status": "idle", "error": "",
                                        "since": 0, "detail": ""})
        s.update(kw)
        return dict(s)


def all_states():
    with _state_lock:
        return {k: dict(v) for k, v in _state.items()}


def _lock_for(host_id):
    with _state_lock:
        return _connect_locks.setdefault(host_id, threading.Lock())


# -------------------------------------------------------------- master ctrl

def master_alive(host):
    if not os.path.exists(control_path(host["id"])):
        return False
    try:
        p = boundedproc.run([SSH, "-F", SSH_CONFIG, "-O", "check", alias(host)],
                            timeout=6, env=env_for(host), stdout_limit=4096,
                            stderr_limit=4096)
        return p.returncode == 0
    except Exception:
        return False


def connect(host, force=False):
    """Open (or verify) the multiplexed master connection for a host."""
    hid = host["id"]
    with _lock_for(hid):
        if not force and master_alive(host):
            set_state(hid, status="online", error="")
            return get_state(hid)
        if force:
            disconnect(host)
        if not host.get("hostname"):
            return set_state(hid, status="error", error="No hostname configured")
        # A host behind a tunnel is not reachable until the tunnel is up, and
        # ssh's own failure for that ("no route to host", eventually) says
        # nothing about the real cause. Bring the VPN up first and report its
        # error verbatim, so the reason you cannot reach the box is the reason
        # the UI shows.
        if host.get("vpn"):
            set_state(hid, status="connecting", error="",
                      detail="opening VPN")
            err = vpn.ensure_up(host["vpn"])
            if err:
                return set_state(hid, status="error", detail="",
                                 error="VPN: %s" % str(err)[:300])
        set_state(hid, status="connecting", error="", detail="")
        t0 = time.time()
        try:
            p = boundedproc.run(
                [SSH, "-F", SSH_CONFIG, "-M", "-N", "-f", alias(host)],
                timeout=45, env=env_for(host), stdout_limit=4096,
                stderr_limit=16384)
        except Exception as e:
            return set_state(hid, status="error", error=str(e))
        latency = int((time.time() - t0) * 1000)
        if p.timed_out:
            return set_state(hid, status="error", error="Connection timed out")
        if p.returncode != 0:
            err = (p.stderr or b"").decode(errors="replace").strip().splitlines()
            msg = err[-1] if err else "ssh exited %d" % p.returncode
            return set_state(hid, status="error", error=msg[:400])
        return set_state(hid, status="online", error="", since=int(time.time()),
                         latency_ms=latency)


def disconnect(host):
    try:
        boundedproc.run([SSH, "-F", SSH_CONFIG, "-O", "exit", alias(host)],
                        timeout=8, env=env_for(host), stdout_limit=4096,
                        stderr_limit=4096)
    except Exception:
        pass
    try:
        os.unlink(control_path(host["id"]))
    except OSError:
        pass
    return set_state(host["id"], status="idle", error="")


# Opening every master at once is fine for five hosts and a thundering herd of
# ssh processes for fifty, so startup fans out through a small window.
_connect_gate = threading.BoundedSemaphore(8)


def connect_all(async_=True):
    def one(h):
        with _connect_gate:
            connect(h)

    def work():
        hosts = hostreg.load()[:64]
        with ThreadPoolExecutor(max_workers=8, thread_name_prefix="fleet-connect") as pool:
            list(pool.map(one, hosts))
    if async_:
        threading.Thread(target=work, daemon=True).start()
    else:
        work()


# ------------------------------------------------------------------ exec

def run(host, command, timeout=30, login_shell=True, input_data=None):
    """Run a command on the host over the shared master. Returns (rc, out, err)."""
    if login_shell:
        argv = base_args(host) + ["--", "sh -c %s" % shlex.quote(command)]
    else:
        argv = base_args(host) + ["--", command]
    try:
        p = boundedproc.run(argv, timeout=timeout, env=env_for(host),
                            input_data=input_data, stdout_limit=2 * 1024 * 1024,
                            stderr_limit=256 * 1024)
        out = p.stdout.decode(errors="replace")
        err = p.stderr.decode(errors="replace")
        if p.stdout_truncated:
            err += "\n[Fleet: stdout truncated at 2 MiB]"
        if p.stderr_truncated:
            err += "\n[Fleet: stderr truncated at 256 KiB]"
        if p.timed_out:
            err += "\n[Fleet: timed out]"
        return p.returncode, out, err.strip()
    except Exception as e:
        return (1, "", str(e))


def run_script(host, script, timeout=60):
    """Pipe a shell script to the remote `sh` -- avoids quoting headaches."""
    argv = base_args(host) + ["--", "sh -s"]
    try:
        p = boundedproc.run(argv, input_data=script, timeout=timeout,
                            env=env_for(host), stdout_limit=2 * 1024 * 1024,
                            stderr_limit=256 * 1024)
        out = p.stdout.decode(errors="replace")
        err = p.stderr.decode(errors="replace")
        if p.stdout_truncated:
            err += "\n[Fleet: stdout truncated at 2 MiB]"
        if p.stderr_truncated:
            err += "\n[Fleet: stderr truncated at 256 KiB]"
        if p.timed_out:
            err += "\n[Fleet: timed out]"
        return p.returncode, out, err.strip()
    except Exception as e:
        return (1, "", str(e))


# ---------------------------------------------------------------- key setup

def list_local_keys():
    d = os.path.expanduser("~/.ssh")
    out = []
    try:
        names = sorted(os.listdir(d))
    except OSError:
        return out
    for n in names:
        p = os.path.join(d, n)
        if not os.path.isfile(p) or n.endswith(".pub") or n in ("config", "known_hosts", "authorized_keys"):
            continue
        try:
            with open(p, "rb") as fh:
                head = fh.read(64)
            if b"PRIVATE KEY" not in head:
                continue
        except OSError:
            continue
        fp = ""
        try:
            r = boundedproc.run([SSH_KEYGEN, "-lf", p], timeout=5,
                                stdout_limit=4096, stderr_limit=4096)
            if r.returncode == 0:
                fp = r.stdout.decode().strip()
        except Exception:
            pass
        out.append({"path": p, "name": n, "fingerprint": fp,
                    "has_pub": os.path.exists(p + ".pub")})
    return out


def generate_key(name="id_ed25519_fleet", comment=None):
    d = os.path.expanduser("~/.ssh")
    os.makedirs(d, mode=0o700, exist_ok=True)
    path = os.path.join(d, name)
    if os.path.exists(path):
        return {"ok": False, "error": "%s already exists" % path}
    comment = comment or "fleet@%s" % os.uname().nodename
    p = boundedproc.run([SSH_KEYGEN, "-t", "ed25519", "-N", "", "-C", comment, "-f", path],
                        timeout=30, stdout_limit=4096, stderr_limit=4096)
    if p.returncode != 0:
        return {"ok": False, "error": p.stderr.decode(errors="replace")}
    return {"ok": True, "path": path,
            "public": open(path + ".pub").read().strip()}


def install_key(host, key_path):
    """Append a public key to the host's authorized_keys, idempotently.

    Uses the existing (possibly password-authenticated) master rather than
    """
    pub = key_path if key_path.endswith(".pub") else key_path + ".pub"
    try:
        material = open(os.path.expanduser(pub)).read().strip()
    except OSError as e:
        return {"ok": False, "error": str(e)}
    script = (
        "set -e\n"
        "mkdir -p ~/.ssh && chmod 700 ~/.ssh\n"
        "touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys\n"
        "key=%s\n"
        'if grep -qF "$key" ~/.ssh/authorized_keys; then echo already; '
        'else printf \'%%s\\n\' "$key" >> ~/.ssh/authorized_keys; echo added; fi\n'
    ) % shlex.quote(material)
    rc, out, err = run_script(host, script, timeout=30)
    if rc != 0:
        return {"ok": False, "error": err.strip() or "exit %d" % rc}
    return {"ok": True, "result": out.strip()}
